-- Tracks user-uploaded assets used for RAG training (OpenAI Vector Stores).
-- Run this in Supabase SQL Editor.

create table if not exists public.agent_knowledge_files (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  kind text not null check (kind in ('pdf', 'image', 'text')),
  original_name text,
  storage_bucket text,
  storage_path text,
  openai_file_id text,
  openai_batch_id text,
  knowledge_id bigint references public.agent_knowledge(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists agent_knowledge_files_user_id_created_at_idx
  on public.agent_knowledge_files (user_id, created_at desc);

alter table public.agent_knowledge_files enable row level security;

drop policy if exists "agent_knowledge_files_select_own" on public.agent_knowledge_files;
create policy "agent_knowledge_files_select_own"
  on public.agent_knowledge_files
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "agent_knowledge_files_insert_own" on public.agent_knowledge_files;
create policy "agent_knowledge_files_insert_own"
  on public.agent_knowledge_files
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "agent_knowledge_files_delete_own" on public.agent_knowledge_files;
create policy "agent_knowledge_files_delete_own"
  on public.agent_knowledge_files
  for delete
  to authenticated
  using (auth.uid() = user_id);
